title: Microservicio del club (Core)
description: Documentacion del microservicio central (core) de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-club"
